// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQcXXml0-_cfjS67pkGmdkUspkupMF58U',
    appId: '1:474178090895:web:b32f187f5e94839bdf3dfa',
    messagingSenderId: '474178090895',
    projectId: 'studymate-studytracker',
    authDomain: 'studymate-studytracker.firebaseapp.com',
    storageBucket: 'studymate-studytracker.firebasestorage.app',
    measurementId: 'G-775FC09FZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcNM9UXrxNmHHm8SAUaFo7XcZtyxvVt0Y',
    appId: '1:474178090895:android:dde27cbf18708566df3dfa',
    messagingSenderId: '474178090895',
    projectId: 'studymate-studytracker',
    storageBucket: 'studymate-studytracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuWFtwrkbhvwtdPwqkuudGkPVePRHFNOY',
    appId: '1:474178090895:ios:4830d216ae3daf23df3dfa',
    messagingSenderId: '474178090895',
    projectId: 'studymate-studytracker',
    storageBucket: 'studymate-studytracker.firebasestorage.app',
    iosBundleId: 'com.example.studymateStudytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuWFtwrkbhvwtdPwqkuudGkPVePRHFNOY',
    appId: '1:474178090895:ios:4830d216ae3daf23df3dfa',
    messagingSenderId: '474178090895',
    projectId: 'studymate-studytracker',
    storageBucket: 'studymate-studytracker.firebasestorage.app',
    iosBundleId: 'com.example.studymateStudytracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQcXXml0-_cfjS67pkGmdkUspkupMF58U',
    appId: '1:474178090895:web:287e2baf3340cc69df3dfa',
    messagingSenderId: '474178090895',
    projectId: 'studymate-studytracker',
    authDomain: 'studymate-studytracker.firebaseapp.com',
    storageBucket: 'studymate-studytracker.firebasestorage.app',
    measurementId: 'G-H6BX36FKB5',
  );
}
